- name: Ensure group "node-exporter" exists
  ansible.builtin.group:
    name: node-exporter
    state: present

- name: Create node_exporter user
  ansible.builtin.user:
    name: "node-exporter"
    group: "node-exporter"
    shell: /usr/sbin/nologin
    system: true
    create_home: false

- name: Download and unzip node_exporter
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes
    validate_certs: no

- name: Move binary to the final destination
  ansible.builtin.copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    owner: "node-exporter"
    group: "node-exporter"
    mode: 0755
    remote_src: yes

- name: Configure node_exporter service
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0755
  notify: reload_daemon_and_restart_node_exporter

- name: Ensure node_exporter service is started
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: yes
