- name: Install nginx
  ansible.builtin.apt:
    name: nginx

- name: Copy nginx configuration as uWSGI frontend
  ansible.builtin.copy:
    src: ../files/default # local
    dest: /etc/nginx/sites-enabled/default # remote
    owner: root
    mode: "0644"
  notify: Restart nginx

- name: Ensure nginx service is started
  ansible.builtin.service:
    name: nginx
    state: started # it's just a check
    enabled: true # it's to start the process
