- name: Install required packages
  ansible.builtin.apt:
    name:
      - nginx
      - prometheus-nginx-exporter

- name: Copy nginx configuration as uWSGI frontend
  ansible.builtin.template:
    src: ../templates/default.j2
    dest: /etc/nginx/sites-enabled/default
    owner: root
    mode: 0644
  notify: Restart nginx

- name: Ensure nginx service is started
  ansible.builtin.service:
    name: "{{ item }}"
    state: started # it's just a check
    enabled: true
  loop:
    - nginx
    - prometheus-nginx-exporter
