- name: Install pgks
  ansible.builtin.apt:
    name:
      - nginx
      - prometheus-nginx-exporter

- name: Copy nginx configuration
  ansible.builtin.template:
    src: ../templates/default.j2
    dest: /etc/nginx/sites-enabled/default
    owner: root
    mode: 0644
  notify: Restart nginx

- name: Ensure services are started
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - nginx
    - prometheus-nginx-exporter
