- name: Install nginx
  ansible.builtin.apt:
    name: nginx

- name: nginx configuration
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: Restart nginx

- name: Ensure services are started
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Install prometheus-nginx-exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter

- name: Ensure prometheus-nginx-exporter is running
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
    enabled: true
