- name: Install nginx
  ansible.builtin.apt:
    name: nginx

- name: Copy Nginx configuration as uWSGI frontend
  ansible.builtin.copy:
    src: ../files/default # local
    dest: /etc/nginx/sites-enabled/default # remote
    owner: agama
    mode: '0644'

- name: ensure Nginx service is started
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true