- name: Install nginx
  apt:
    name:
      - nginx
      - prometheus-nginx-exporter

- name: nginx configuration
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
    #validate: /usr/sbin/nginx -t -c %s
  notify: Restart nginx

- meta: flush_handlers

- name: Ensure services are started
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - nginx
    - prometheus-nginx-exporter
