- name: Install nginx
  ansible.builtin.apt:
    name: nginx

- name: Copy nginx configuration
  ansible.builtin.template:
    src: ../templates/default.j2
    dest: /etc/nginx/sites-enabled/default
    owner: root
    mode: 0644
  notify: Restart nginx

- name: Ensure nginx is started
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Install prometheus-nginx-exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter

- name: Ensure prometheus-nginx-exporter service is started
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
    enabled: true
