- apt:
    name: 
      - haproxy
      - keepalived

- template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- template
    src: keepalived.conf.j2
    dest: 
  notify: Restart keepalived