- name: Install prerequisite packages
  ansible.builtin.apt:
    name:
      - wget

- name: Download InfluxDB
  ansible.builtin.get_url:
    url: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_amd64.deb
    dest: /tmp/influxdb_1.8.10_amd64.deb

- name: Install InfluxDB
  ansible.builtin.apt:
    deb: /tmp/influxdb_1.8.10_amd64.deb
    state: present

- name: Ensure influxdb is running
  ansible.builtin.service:
    name: influxdb
    state: started
    enabled: true

- name: Add GPG key
  ansible.builtin.apt_key:
    url: https://repos.influxdata.com/influxdata-archive_compat.key
    state: present

- name: Add stable repository
  ansible.builtin.apt_repository:
    repo: deb https://repos.influxdata.com/debian buster stable
    state: present

- name: Install telegraf
  ansible.builtin.apt:
    name: telegraf=1.28.2-1
    state: present

- name: Telegraf config
  ansible.builtin.copy:
    src: ../files/telegraf.conf
    dest: /etc/telegraf/telegraf.conf
  notify: Restart Telegraf

- name: Ensure Telegraf is running
  ansible.builtin.service:
    name: telegraf
    state: started
    enabled: true
