- name: Install prerequisite packages
  ansible.builtin.apt:
    name:
      - wget

- name: Download InfluxDB
  ansible.builtin.get_url:
    url: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_amd64.deb
    dest: /tmp/influxdb_1.8.10_amd64.deb

- name: Install InfluxDB
  ansible.builtin.apt:
    deb: /tmp/influxdb_1.8.10_amd64.deb
    state: present

- name: Add GPG key
  ansible.builtin.apt_key:
    url: https://repos.influxdata.com/influxdata-archive_compat.key
    state: present

- name: Add stable repository
  ansible.builtin.apt_repository:
    repo: deb https://repos.influxdata.com/debian buster stable
    state: present

- name: Install telegraf
  ansible.builtin.apt:
    name: telegraf=1.28.2-1
    state: present

#- name: Telegraf configurations
#  ansible.builtin.template:
#    src: ../templates/telegraf.conf.j2
#    dest: /etc/telegraf/telegraf.conf
#  notify: Restart Telegraf
#
#- name: InfluxDB configurations
#  ansible.builtin.template:
#    src: ../templates/influxdb.conf.j2
#    dest: /etc/influxdb/influxdb.conf
#  notify: Restart InfluxDB

- name: Add the user 'pinger'
  ansible.builtin.user:
    name: pinger

- name: Create pinger dir
  ansible.builtin.file:
    path: /etc/pinger
    state: directory

- name: pinger config
  ansible.builtin.copy:
    src: ../templates/pinger.conf.j2
    dest: /etc/pinger/pinger.conf
  notify: Restart pinger

- name: pinger script
  ansible.builtin.copy:
    src: ../files/pinger.sh
    dest: /usr/local/bin/pinger
    mode: 0755

  notify: Restart pinger

- name: ping service config
  ansible.builtin.template:
    src: ../templates/pinger.service.j2
    dest: /etc/systemd/system/pinger.service
  notify: Restart pinger

- name: Ensure services are running
  ansible.builtin.systemd:
    daemon_reload: true # if tomorrow doesn't work, try writing this module on a separate task
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - influxdb
    - pinger
  tags: cc
