- name: Install prerequisite packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - software-properties-common
      - wget

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /etc/apt/keyrings/
    state: directory
    mode: "0755"

- name: Get GPG key
  ansible.builtin.shell: wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/grafana.gpg > /dev/null

- name: Add stable repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main
    filename: /etc/apt/sources.list.d/grafana.list

- name: Add beta repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com beta main
    filename: /etc/apt/sources.list.d/grafana.list

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
#- name: Copy Grafana configuration
#  ansible.builtin.template:
#    src: ../templates/server.domain.j2
#    dest: /etc/nginx/sites-enabled/default
#    owner: root
#    mode: "0644"
#  notify: Restart nginx
