- name: Install uwsgi package
  ansible.builtin.apt:
      name: uwsgi

- name: Install uwsgi-plugin-python3 package
  ansible.builtin.apt:
      name: uwsgi-plugin-python3

- name: Copy uwsgi configuration for agama
  ansible.builtin.copy:
    src: ../files/agama.ini # TODO: check this path is right
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: '0644'
  
# this task has always to be after the one that manages service configuration
- name: ensure uWSGI service is running
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: true