- name: Install the packages "uwsgi" and "uwsgi-plugin-python3"
  apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3

- name: uWSGI configuration for agama
  template:
    src: agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
  no_log: true
  notify: Restart uWSGI

- name: Ensure uWSGI service is started
  service:
    name: uwsgi
    state: started
    enabled: true
