---
- name: Initial setup
  hosts: all
  roles:
    - init

- name: DNS servers
  hosts: dns_server
  roles:
    - bind

- name: Resolvers
  hosts: all
  roles:
    - resolvers

- name: Install monitoring stack
  hosts: prometheus_server
  become: yes
  roles:
    - prometheus
#    - grafana

# I think it needs to run after prometheus
- name: Reverse Proxy
  hosts: nginx_reverse_proxy_server
  roles:
    - nginx-reverse-proxy-server

- name: Install node-exporter
  hosts: all
  become: yes #  allows you to ‘become’ another user, different from the user that logged into the machine (remote user)
  roles:
    - node-exporter

- name: Database server
  hosts: db_servers
  roles:
    - mysql

- name: Web server
  hosts: web_servers
  roles:
    - agama
    - uwsgi
    - nginx
