---
- name: Initial setup
  hosts: all
  roles:
    - init

- name: DNS servers
  hosts: dns_server
  roles:
    - bind

- name: Resolvers
  hosts: all
  roles:
    - resolvers

- name: Install monitoring stack
  hosts: prometheus_server
  become: yes
  roles:
    - prometheus
    #- grafana
    - nginx

- name: Database server
  hosts: db_servers
  roles:
    - mysql

- name: Web server
  hosts: web_servers
  roles:
    - agama
    - uwsgi
    - nginx
# I could add some tag here just to run specific plays
