---
- name: Initial setup
  hosts: all
  roles:
    - init
  tags: init

- name: DNS servers
  hosts: dns_server
  roles:
    - bind
  tags: dns

- name: Resolvers
  hosts: all
  roles:
    - resolvers
  tags: dns

- name: Install monitoring stack
  hosts: prometheus_server
  become: yes
  roles:
    - prometheus
    - grafana
    - nginx
  tags: p

- name: Database server
  hosts: db_servers
  roles:
    - mysql
  tags: db

- name: Web servers
  hosts: web_servers
  roles:
    - agama
    - uwsgi
    - nginx
  tags: ws
