---
- name: Initial setup
  hosts: all
  roles:
    - init
  tags: init

- name: DNS servers
  hosts: dns_servers
  roles:
    - bind
  tags: dns

- name: Resolvers
  hosts: all
  roles:
    - resolvers
  tags: dns

- name: Prometheus server
  hosts: prometheus_servers
  roles:
    - prometheus
    - nginx
  tags: p

- name: Docker server
  hosts: docker_servers
  roles:
    - docker
  tags: d

- name: Grafana server
  hosts: grafana_servers
  roles:
    - grafana
    - nginx
  tags: g

- name: Database server
  hosts: db_servers
  roles:
    - mysql
  tags: db

- name: Web servers
  hosts: web_servers
  roles:
    - agama
    - nginx
  tags: ws

- name: InfluxDB
  hosts: influxdb_servers
  roles:
    - influxdb
  tags: i

- name: pinger
  hosts: pinger_servers
  roles:
    - pinger
  tags: pg
