---
- name: Gather facts
  gather_facts: yes
  hosts: all
  tags:
      - init
      - b
      - r
      - db
      - d
      - a
      - ha
      - k
      - i
      - pg
      - p
      - g
      - nx

- name: Initial setup
  hosts: all
  roles:
      - init
  tags: init

- name: DNS servers
  hosts: dns_servers
  roles:
      - bind
  tags: b

- name: Resolvers
  hosts: all
  roles:
      - resolvers
  tags: r

- name: Database server
  hosts: db_servers
  roles:
      - mysql
  tags: db

- name: Docker servers
  hosts: docker_servers
  roles:
      - docker
  tags: d

- name: agama servers
  hosts: agama_servers
  roles:
      - agama
  tags: a

- name: haproxy
  hosts: haproxy_servers
  roles:
      - haproxy
  tags: ha

- name: keepalived
  hosts: keepalived_servers
  roles:
      - keepalived
  tags: k

- name: InfluxDB
  hosts: influxdb_servers
  roles:
      - influxdb
  tags: i

- name: pinger
  hosts: pinger_servers
  roles:
      - pinger
  tags: pg

- name: Prometheus server
  hosts: prometheus_servers
  roles:
      - prometheus
  tags: p

- name: Grafana server
  hosts: grafana_servers
  roles:
      - grafana
  tags: g

- name: nginx server
  hosts: nginx_servers
  roles:
      - nginx
  tags: nx
