---
- name: Initial setup
  hosts: all
  #become: yes
  roles:
    - init
  tags: init

- name: DNS servers
  hosts: dns_servers
  #become: yes
  roles:
    - bind
  tags: dns

- name: Resolvers
  hosts: all
  #become: yes
  roles:
    - resolvers
  tags: dns

- name: Prometheus server
  hosts: prometheus_servers
  #become: yes
  roles:
    - prometheus
    - nginx
  tags: p

- name: Grafana server
  hosts: grafana_servers
  #become: yes
  roles:
    - grafana
  tags: g

- name: Database server
  hosts: db_servers
  #become: yes
  roles:
    - mysql
  tags: db

- name: Web servers
  hosts: web_servers
  #become: yes
  roles:
    - agama
    - uwsgi
    - nginx
  tags: ws

- name: InfluxDB
  hosts: influxdb_servers
  #become: yes
  roles:
    - influxdb
  tags: i

- name: pinger
  hosts: pinger_servers
  #become: yes
  roles:
    - pinger
  tags: pg
