---
- name: Initial setup
  hosts: all
  roles:
    - init
  tags: init

- name: DNS servers
  hosts: dns_servers
  roles:
    - bind
  tags: dns

- name: Resolvers
  hosts: all
  roles:
    - resolvers
  tags: dns

- name: Database server
  hosts: db_servers
  roles:
    - mysql
  tags: db

- name: Docker server
  hosts: docker_servers
  roles:
    - docker
    - agama
  tags: d

- name: haproxy
  hosts: haproxy_servers
  roles:
    - haproxy
  tags: ha

- name: keepalived
  hosts: keepalived_servers
  roles:
    - keepalived
  tags: k

- name: InfluxDB
  hosts: influxdb_servers
  roles:
    - influxdb
  tags: i

- name: pinger
  hosts: pinger_servers
  roles:
    - pinger
  tags: pg

- name: Prometheus server
  hosts: prometheus_servers
  roles:
    - prometheus
    - nginx
  tags: p

- name: Grafana server
  hosts: grafana_servers
  roles:
    - grafana
    - nginx
  tags: g
