---
- name: Initial setup
  hosts: all
  roles:
    - init
  tags: init

- name: DNS servers
  hosts: dns_server
  roles:
    - bind
  tags: dns

- name: Resolvers
  hosts: all
  roles:
    - resolvers
  tags: dns

- name: Prometheus server
  hosts: prometheus_server
  become: yes
  roles:
    - prometheus
    - nginx
  tags: p

- name: Grafana server
  hosts: grafana_server
  become: yes
  roles:
    - grafana
  tags: g

- name: Database server
  hosts: db_servers
  roles:
    - mysql
  tags: db

- name: Web servers
  hosts: web_servers
  roles:
    - agama
    - uwsgi
    - nginx
  tags: ws

- name: InfluxDB
  hosts: influxdb
  roles:
  #    - influxdb
  tags: i
