# Configuration file version
apiVersion: 1

# List of data sources to insert/update depending on what's
# available in the database.
datasources:
  - name: Prometheus
    type: Prometheus
    access: proxy
    orgId: 1
    url: http://alessandrotambellini-2:9090 # TODO: make it dynamic. This is hard coded
    version: 1
    editable: false
