# Configuration file version
apiVersion: 1

# List of data sources to insert/update depending on what's
# available in the database.
datasources:
  - name: Prometheus-1
    type: prometheus
    access: proxy
    url: http://alessandrotambellini-2:9090/prometheus # TODO: make it dynamic. This is hard coded
  - name: influxdb:latency
    type: influxdb
    access: proxy
    url: http://alessandrotambellini-2.rabix.io:8086
    database: latency
  - name: influxdb:telegraf
    type: influxdb
    access: proxy
    url: http://alessandrotambellini-2:8086
    database: logging
#    dashboard: 12433
