{
 "title": "Main",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "InfluxDB Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "nginx",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Bind",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "HAProxy server",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_server_up", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "HAProxy",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "MySQL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "keepalived vrrp state",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "InfluxDB write rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    { "expr": "influxdb_write_write_ok", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"idle\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[5m])",
     "legendFormat": "{{ instance }} nginx"
    }
   ]
  },
  {
   "title": "latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rtt",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MySQL selects per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory consumption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "DNS queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}