- name: Add the user 'agama'
  user:
    name: agama

- name: Set directory ownership to 'agama'
  file:
    path: /opt/agama
    owner: agama
    state: directory

- name: Install required packages
  apt:
    name:
      - python3-flask-sqlalchemy
      - python3-pymysql

- name: Download agama webapp
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama/
