- name: Add the user {{ agama_user }}
  user:
      name: "{{ agama_user }}"

- name: Set directory ownership to {{ agama_user }}
  file:
      path: /opt/agama
      owner: "{{ agama_user }}"
      state: directory

- name: Install required packages
  apt:
      name:
          - python3-flask-sqlalchemy
          - python3-pymysql

- name: Download agama webapp
  get_url:
      url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
      dest: /opt/agama/
