- name: Add the user 'agama'
  ansible.builtin.user:
    name: agama

- name: Set directory ownership to 'agama'
  ansible.builtin.file:
    path: /opt/agama
    owner: agama
    state: directory

- name: Install required packages
  ansible.builtin.apt:
    name:
      - python3-flask-sqlalchemy
      - python3-pymysql

- name: Download agama webapp
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama/
# TODO: I may need to set some permissions/ownership --> watch video lesson
