- name: restart prometheus-node-exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: restarted

- name: restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
