- name: prometheus-mysqld-exporter user configuration
  ansible.builtin.template:
    src: .my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
    mode: 0400
    owner: prometheus
  no_log: true

- name: Install required packages
  ansible.builtin.apt:
    name:
      - mysql-server
      - python3-pymysql
      - prometheus-mysqld-exporter

- name: MySQL exporter user
  community.mysql.mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    priv: "*.*:PROCESS, REPLICATION CLIENT, SELECT" # privileges
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: Ensure MySQL services are started
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - mysql
    - prometheus-mysqld-exporter

# mysql db is after the mysql server is started because you cannot create a db if the server is down
- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ agama_db }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL {{ mysql_user }} user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ agama_db }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: MySQL configuration
  ansible.builtin.copy:
    src: bind_address.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart MySQL

#
# backup
#

- name: create backup dir
  ansible.builtin.file:
    path: /home/backup/mysql
    owner: backup
    state: directory

- name: backup user
  community.mysql.mysql_user:
    name: backup
    password: "{{ backup_password }}"
    priv: "{{ agama_db }}.*:LOCK TABLES,SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: Client config
  ansible.builtin.template:
    src: .backup.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    mode: 0400
  no_log: true

- name: Cron config
  ansible.builtin.template:
    src: mysql-backup.j2
    dest: /etc/cron.d/mysql-backup
