- name: Copy mysql exporter user configuration
  ansible.builtin.template:
    src: ../templates/.my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
    mode: 0400
    owner: prometheus
  no_log: true

- name: Install required packages
  ansible.builtin.apt:
    name:
      - mysql-server
      - python3-pymysql
      - prometheus-mysqld-exporter

- name: MySQL exporter user
  community.mysql.mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    priv: "*.*:PROCESS, REPLICATION CLIENT, SELECT" # privileges
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: Ensure MySQL services are started
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - mysql
    - prometheus-mysqld-exporter

# mysql db is after the mysql server is started because you cannot create a db if the server is down
- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL {{ mysql_user }} user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL" # the user has access only to its own database
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: Copy MySQL configuration
  ansible.builtin.copy:
    src: ../files/bind_address.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
    owner: root
    mode: "0644"
  notify: Restart MySQL
