- name: Install prerequisite pkgs
  apt:
    name: fping

- name: Add the user 'pinger'
  user:
    name: pinger

- name: Create pinger dir
  file:
    path: /etc/pinger
    state: directory

- name: pinger config
  template:
    src: pinger.conf.j2
    dest: /etc/pinger/pinger.conf
  notify: Restart pinger

- name: pinger script
  copy:
    src: pinger.sh
    dest: /usr/local/bin/pinger
    mode: 0755
  notify: Restart pinger

- name: ping service config
  template:
    src: pinger.service.j2
    dest: /etc/systemd/system/pinger.service
  notify: Restart pinger

- name: Ensure pinger is running
  systemd:
    daemon_reload: true
    name: pinger
    state: started
    enabled: true
