- name: Restart InfluxDB
  ansible.builtin.service:
    name: influxdb
    state: restarted

- name: Restart Telegraf
  ansible.builtin.service:
    name: telegraf
    state: restarted

- name: Restart prometheus-influxdb-stats-exporter
  ansible.builtin.systemd:
    name: prometheus-influxdb-stats-exporter # this is the name of the service, not of the executable
    state: restarted
