- name: Restart InfluxDB
  service:
    name: influxdb
    state: restarted

- name: Restart Telegraf
  service:
    name: telegraf
    state: restarted

- name: Restart prometheus-influxdb-stats-exporter
  systemd:
    name: prometheus-influxdb-stats-exporter # this is the name of the service, not of the executable
    state: restarted
