- name: Install keepalived
  apt:
      name:
          - keepalived

- name: Create user 'keepalived_script'
  user:
      name: keepalived_script

- name: Create dir 'keepalived_script'
  file:
      path: /home/keepalived_script
      state: directory
      owner: keepalived_script

- name: haproxy script
  copy:
      src: check_haproxy.sh
      dest: /home/keepalived_script/check_haproxy.sh
      mode: 0755
  notify: Restart keepalived

- name: Keepalived config
  template:
      src: keepalived.conf.j2
      dest: /etc/keepalived/keepalived.conf
  notify: Restart keepalived

#
#
#  exporter
#

- name: Download keepalived-exporter
  get_url:
      url: https://github.com/mehdy/keepalived-exporter/releases/download/v1.3.2/keepalived-exporter-1.3.2.linux-amd64.tar.gz
      dest: /tmp/keepalived-exporter-1.3.2.linux-amd64.tar.gz

- name: Unarchive keepalived-exporter
  unarchive:
      remote_src: true
      src: /tmp/keepalived-exporter-1.3.2.linux-amd64.tar.gz
      dest: /tmp

- name: Move keepalived-exporter executable
  copy:
      remote_src: true
      src: /tmp/keepalived-exporter
      dest: /usr/local/bin/
      mode: 0755

- name: keepalived-exporter config
  template:
      src: keepalived-exporter.service.j2
      dest: /etc/systemd/system/keepalived-exporter.service
  notify: Restart keepalived-exporter

#
#
# Run services
#

- name: Ensure keepalived is running
  service:
      name: keepalived
      state: started
      enabled: true

- name: Ensure keepalived-exporter service is running
  systemd:
      name: keepalived-exporter
      state: started
      enabled: true
      daemon_reload: true

#
#
# CNAME
#

- include_role:
      name: dns_record
  vars:
      dns_record:
          "ka{{ inventory_hostname | replace('AlessandroTambellini', '') }}"
