- name: Install Prometheus
  apt:
      name: prometheus

- name: Prometheus args
  template:
      src: prometheus.j2
      dest: /etc/default/prometheus
  notify: Restart prometheus

- name: Configure Prometheus
  template:
      src: prometheus.yml.j2
      dest: "/etc/prometheus/prometheus.yml"
      mode: 0755
      owner: "{{ prometheus_user }}"
  notify: Restart prometheus

- name: Ensure Prometheus service is started
  service:
      name: prometheus
      state: started
      enabled: yes

#
#
# CNAME
#

- include_role:
      name: dns_record
  vars:
      dns_record: prometheus
