- name: Install Prometheus
  ansible.builtin.apt:
    name: prometheus

- name: Prometheus args
  ansible.builtin.template:
    src: prometheus.j2
    dest: /etc/default/prometheus
  notify: restart_prometheus

- name: Configure Prometheus
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "/etc/prometheus/prometheus.yml"
    mode: 0755
    owner: prometheus
  notify: restart_prometheus

- name: Ensure Prometheus service is started
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: yes
