- name: Restart MySQL
  service:
      name: mysql
      state: restarted

- name: Restart prometheus-mysqld-exporter
  service:
      name: prometheus-mysqld-exporter
      state: restarted

- name: Reset MySQL source
  community.mysql.mysql_replication:
      mode: "{{ item }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
      - stopreplica
      - resetprimary
  when: inventory_hostname in groups['db_primary']

# this is the task that allows the transport of data from primary to secondary
- name: Reset MySQL replica
  community.mysql.mysql_replication:
      mode: "{{ item }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock
      primary_host:
          "{{ cname_mysql }}{{ groups['db_primary'][0] |
          replace('AlessandroTambellini', '') }}"
      primary_user: "{{ replication_user }}"
      primary_password: "{{ replication_password }}"
  loop:
      - stopreplica
      - changeprimary
      - resetreplica
      - startreplica
  when: inventory_hostname not in groups['db_primary']
  no_log: true
