# it's necessary to stop systemd-resolved before updating the DNS settings
- name: Stop service systemd-resolved, if started
  service:
    name: systemd-resolved
    state: stopped

- name: Update VM DNS settings
  template:
    src: DNS_settings.j2
    dest: /etc/resolv.conf
