# it's necessary to stop systemd-resolved before updating the DNS settings
- name: Stop service systemd-resolved, if started
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped

- name: Update VM DNS settings
  ansible.builtin.template:
    src: ../templates/DNS_settings.j2
    dest: /etc/resolv.conf
