- name: Install required pkgs
  apt:
    name:
      - bind9
      - prometheus-bind-exporter
      - python3-dnspython

- name: bind9 named.conf.options
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    validate: /usr/sbin/named-checkconf %s
  notify: Restart bind9
  no_log: true

- name: bind9 named.conf.local
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: Restart bind9

- name: primary zone config
  template:
    src: db.rabix.io.j2
    dest: "/var/cache/bind/db.rabix.io"
    force: false # while testing/developing disable it
  notify: Restart bind9
  when: inventory_hostname in groups['dns_primary']

- name: rev zone config
  template:
    src: db.rev.j2
    dest: "/var/cache/bind/db.rev"
    force: false # while testing/developing disable it
  notify: Restart bind9
  when: inventory_hostname in groups['dns_primary']

- meta: flush_handlers

- name: Ensure services are started
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - bind9
    - prometheus-bind-exporter

- name: Set A record for backup server
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ dns_nsupdate_key }}"
    server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"
    zone: "{{ domain_name }}"
    record: backup
    value: "{{ backup_server_ip }}"
    type: "A"

#  when: inventory_hostname in groups['dns_primary']

- include_role:
    name: dns_record
  vars:
    dns_record: "ns{{ inventory_hostname | replace('AlessandroTambellini', '') }}"
