- name: Install "bind9" package
  ansible.builtin.apt:
    name: bind9

- name: Copy bind9 configuration
  ansible.builtin.template:
    src: ../templates/bind9_config.j2
    dest: /etc/bind/named.conf.options
    owner: root
    mode: "0644"
  notify: Restart bind9

- name: Copy master-zone configuration
  ansible.builtin.template:
    src: ../templates/master-zone_config.j2
    dest: /var/lib/bind/db.rabix.io
    owner: root
    mode: "0644"
# notify: Restart bind9 # I do not need to restart the service because is not a config file
# Instead, to update the DNS settings I need to run the below command
- name: Run "rndc reload" to update primary(master) zone file
  ansible.builtin.command: rndc reload

- name: Ensure bind9 service is started
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: true
