- name: Install required packages
  apt:
    name:
      - bind9
      - prometheus-bind-exporter

- name: bind9 configuration
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind9

- name: master-zone configuration
  template:
    src: db.rabix.io.j2
    dest: "/var/lib/bind/db.{{ domain_name }}"
  notify: Run rndc reload

- name: Ensure services are started
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - bind9
    - prometheus-bind-exporter
