#- name: Add the user 'juri'
#  ansible.builtin.user:
#    name: juri

#- name: Add the user 'roman'
#  ansible.builtin.user:
#    name: roman

#- name: Set authorized SSH keys taken from url
#  ansible.posix.authorized_key:
#    user: juri
#    state: present
#    key: https://github.com/hudolejev.keys

#- name: Set authorized SSH keys taken from url
#  ansible.posix.authorized_key:
#    user: roman
#    state: present
#    key: https://github.com/romankuchin.keys

#- name: Update APT cache
#  ansible.builtin.apt:
#    cache_valid_time: 86400

# check if an ansible variable exists and, in case, its content
#- debug:
#    var: hostvars['AlessandroTambellini-1']
#  tags: ct

- name: Add the user 'backup'
  ansible.builtin.user:
    name: backup
    home: /home/backup
    generate_ssh_key: true

- name: Add SSH key
  ansible.builtin.template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
    mode: 0644

- name: Install required packages and set caching time
  ansible.builtin.apt:
    name:
      - ca-certificates=20230311ubuntu0.20.04.1
      - prometheus-node-exporter
    cache_valid_time: 86400

- name: prometheus-node-exporter configuration
  ansible.builtin.template:
    src: prometheus_node_exporter.service.j2
    dest: /etc/systemd/system/prometheus_node_exporter.service
  notify: restart prometheus-node-exporter

- name: Ensure prometheus-node-exporter is running
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: yes

- name: rsyslog config for Telegraf
  ansible.builtin.template:
    src: 15-telegraf.conf.j2
    dest: /etc/rsyslog.d/15-telegraf.conf
  notify: restart rsyslog

- name: Ensure rsyslog is running
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: yes
