#- name: Add the user 'juri'
#  ansible.builtin.user:
#    name: juri

#- name: Add the user 'roman'
#  ansible.builtin.user:
#    name: roman

#- name: Set authorized SSH keys taken from url
#  ansible.posix.authorized_key:
#    user: juri
#    state: present
#    key: https://github.com/hudolejev.keys

#- name: Set authorized SSH keys taken from url
#  ansible.posix.authorized_key:
#    user: roman
#    state: present
#    key: https://github.com/romankuchin.keys

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400
#- name: Collect all ansible data
#  ansible.builtin.setup:
#
#- name: Display all variables/facts known for a host
#  ansible.builtin.debug:
#    var: hostvars[inventory_hostname]['ansible_all_ipv4_addresses']

#- name: Download node_exporter
#  ansible.builtin.get_url: # TODO: setup a script to get the version of node exporter
#    url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_v }}/node_exporter-{{ node_exporter_v }}.linux-amd64.tar.gz
#    dest: /tmp
#    mode: "0440"
#
#- name: Unarchive node_exporter-{{ node_exporter_v }}.linux-amd64.tar.gz
#  ansible.builtin.unarchive:
#    src: /tmp/node_exporter-{{ node_exporter_v }}.linux-amd64.tar.gz
#    dest: /tmp
#    remote_src: yes
#
#- name: Move node_exporter to /usr/local/bin
#  ansible.builtin.copy:
#    src: /tmp/node_exporter-{{ node_exporter_v }}.linux-amd64/node_exporter
#    remote_src: yes
#    dest: /usr/local/bin/node_exporter
#    owner: root
#    mode: "0755"
#
#- name: Install unit file to systemd
#  ansible.builtin.template:
#    src: ../templates/node_exporter.service.j2
#    dest: /etc/systemd/system/node_exporter.service
#    owner: root
#    mode: "0600"
#
#- name: Configure systemd to use node_exporter.service
#  ansible.builtin.systemd:
#    name: node_exporter.service
#    state: started
#    daemon_reload: true
#    enabled: true

- name: Download and unarchive node_exporter
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes
    mode: 0755

- name: Move binary to the final destination
  ansible.builtin.copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    owner: "node-exporter"
    mode: 0755
    remote_src: yes

- name: Create node_exporter user.
  user:
    name: node_exporter
    shell: /sbin/nologin
    state: present

- name: Copy the node_exporter systemd unit file.
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: 0644
  register: node_exporter_service

- name: Reload systemd daemon if unit file is changed.
  systemd:
    daemon_reload: true
  notify: restart node_exporter
  when: node_exporter_service is changed

- name: Ensure node_exporter service is started
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: yes
