#- name: Add the user 'juri'
#  user:
#    name: juri

#- name: Add the user 'roman'
#  user:
#    name: roman

#- name: Set authorized SSH keys taken from url
#  ansible.posix.authorized_key:
#    user: juri
#    state: present
#    key: https://github.com/hudolejev.keys

#- name: Set authorized SSH keys taken from url
#  ansible.posix.authorized_key:
#    user: roman
#    state: present
#    key: https://github.com/romankuchin.keys

#- name: Update APT cache
#  apt:
#    cache_valid_time: 86400

#- debug:
#    var: ansible_architecture

#- name: Gather facts
#  setup:
#
#- name: Display network interfaces
#  debug:
#    var: ansible_facts['interfaces']
#

- name: Install required packages and set caching time
  apt:
      name:
          - ca-certificates=20230311ubuntu0.20.04.1
          - prometheus-node-exporter
          - duplicity
      cache_valid_time: 86400

- name: prometheus-node-exporter configuration
  template:
      src: prometheus_node_exporter.service.j2
      dest: /etc/systemd/system/prometheus_node_exporter.service
  notify: restart prometheus-node-exporter

- name: rsyslog config for Telegraf
  template:
      src: 15-telegraf.conf.j2
      dest: /etc/rsyslog.d/15-telegraf.conf
  notify: restart rsyslog

- name: Ensure services are running
  service:
      name: "{{ item }}"
      state: started
      enabled: yes
  loop:
      - prometheus-node-exporter
      - rsyslog

#
# backup
#

- name: Add the user {{ backup_user }}
  user:
      name: "{{ backup_user }}"
      home: "/home/{{ backup_user }}"
      generate_ssh_key: true
      state: present
      system: true
      create_home: true
      shell: /bin/bash

- name: Add SSH key
  template:
      src: known_hosts.j2
      dest: /home/backup/.ssh/known_hosts
      owner: "{{ backup_user }}"
      group: backup
  no_log: true

- name: create "restore" dir
  file:
      path: "/home/{{ backup_user }}/restore"
      owner: "{{ backup_user }}"
      state: directory
      mode: 0755
