#- name: Add the user 'juri'
#  ansible.builtin.user:
#    name: juri

#- name: Add the user 'roman'
#  ansible.builtin.user:
#    name: roman

#- name: Set authorized SSH keys taken from url
#  ansible.posix.authorized_key:
#    user: juri
#    state: present
#    key: https://github.com/hudolejev.keys

#- name: Set authorized SSH keys taken from url
#  ansible.posix.authorized_key:
#    user: roman
#    state: present
#    key: https://github.com/romankuchin.keys

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400
#- name: Collect all ansible data
#  ansible.builtin.setup:
#
#- name: Display all variables/facts known for a host
#  ansible.builtin.debug:
#    var: hostvars[inventory_hostname]
#- name: Print groups['all']
#  debug:
#    var: groups['dns_server']

- name: Install prometheus-node-exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter

- name: Copy prometheus-node-exporter configuration
  ansible.builtin.template:
    src: prometheus_node_exporter.service.j2
    dest: /etc/systemd/system/prometheus_node_exporter.service
    mode: 0644
  notify: restart prometheus-node-exporter

- name: Ensure prometheus-node-exporter service is started
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: yes

- name: Install ca-certificates
  ansible.builtin.apt:
    name: ca-certificates
